name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          npm i @lithium/sfc @node-lambdas/cli

      - name: Publish to AppHorde Registry
        env:
          CDN_API_URL: ${{ secrets.CDN_API_URL }}
          CDN_API_KEY: ${{ secrets.CDN_API_KEY }}
        run: |
          export baseDir=components
          export PATH="./node_modules/.bin:$PATH"

          for scope in $(ls -1 components); do
            echo "Entering $scope"
            for component in $(ls -1 components/$scope); do
              name=$(echo $component | sed s/.html//)
              echo -n "Publishing $scope/$name... "
              cat $baseDir/$scope/$component | fn lit-ce --name $name | fn es-minify --module true | curl -sS --fail -H "Authorization: ${{ env.CDN_API_KEY }}" ${{ env.CDN_API_URL }}/$scope/$name@0.0.0 --data-binary @-
            done
          done
