name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          npm i @li3/sfc @node-lambdas/cli

      - name: Publish to AppHorde Registry
        env:
          CDN_API_URL: ${{ secrets.CDN_API_URL }}
          CDN_API_KEY: ${{ secrets.CDN_API_KEY }}
        run: |
          bash publish.sh
